export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

/**  USER TYPES  */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const ADD_USER_ADMINISTRATOR ="ADD_USER_ADMINISTRATOR" ;
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const VERIF_PASS = "VERIF_PASS";
export const UPDATING_PASS = "UPDATING_PASS";
export const CURRENT_PERMISSION="CURRENT_PERMISSION"
